# -*- coding: utf-8 -*-
"""PIA_2086092.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ziFX7RVMG03LliYQMNLXzwa3jrtvVqbv
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt

###
url = "https://raw.githubusercontent.com/cesar3245/Mineria-de-datos/main/Practica%201/dataset/Police%20Data.csv"
ds = pd.read_csv(url)
###

###
ds = ds.drop(columns=['country_name', 'search_type','driver_age_raw'])

ds = ds.dropna(axis=0, how='any')

ds = ds[ds['stop_duration'] != '2']
###

###
ds['stop_date'] = pd.to_datetime(ds['stop_date'], format='%m/%d/%Y', errors='coerce')

ds['stop_year'] = ds['stop_date'].dt.year
ds['stop_month'] = ds['stop_date'].dt.month
ds['stop_day'] = ds['stop_date'].dt.day
ds['stop_wday'] = ds['stop_date'].dt.day_name()
###

###
stop_time2 = pd.to_datetime(ds['stop_time'], format='%H:%M', errors='coerce')

ds['stop_hour'] = stop_time2.dt.hour
ds['stop_minute'] = stop_time2.dt.minute
###

###
ds = ds.dropna(subset=['stop_year', 'stop_month', 'stop_day', 'stop_wday', 'stop_hour', 'stop_minute'])
###

###
ds2 = ds.drop(columns=['stop_date','stop_time'])
###

###
ds3 = ds2.copy()

ds3['search_conducted'] = ds3['search_conducted'].astype(int)
ds3['drugs_related_stop'] = ds3['drugs_related_stop'].astype(int)
ds3['driver_gender'] = ds3['driver_gender'].map({'M': 1, 'F': 0})
ds3['is_arrested'] = ds3['is_arrested'].map({'True': 1, 'False': 0, True: 1, False: 0})
###

###
ds3_cat = ds3.select_dtypes(include='object').columns.tolist()

cat_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

ds3_cat_tr = cat_encoder.fit_transform(ds3[ds3_cat])

ds3_cat_df = pd.DataFrame(ds3_cat_tr, columns=cat_encoder.get_feature_names_out(ds3_cat), index=ds3.index)

ds4 = pd.concat([ds3.drop(columns=ds3_cat), ds3_cat_df], axis=1)
###

###
ds5 = ds4.copy()
###

binarias  = [i for i in ds5.columns if ds5[i].dropna().nunique() == 2]
numericas = [i for i in ds5.select_dtypes(include=[np.number]).columns if i not in binarias]

base = ds5[numericas].agg(['mean', 'median', 'var', 'std', 'min', 'max']).T
base['range'] = base['max'] - base['min']
mode_v = ds5[numericas].apply(lambda s: s.mode().iloc[0] if not s.mode().empty else np.nan)

tabla_num = (base.drop(columns=['min','max']).assign(Mode=mode_v)[['mean', 'median','Mode', 'var', 'std', 'range']].rename(columns={'mean': 'Mean', 'median': 'Median', 'var': 'Variance', 'std': 'Std Dev', 'range': 'Range'}).round(3))

tabla_bin = pd.DataFrame({'Proportion': ds5[binarias].mean(), 'Count_1s'  : ds5[binarias].sum()})

def cats(name):
    if name.startswith("stop_outcome"):
        return "Stop Outcome"
    elif name.startswith("stop_duration"):
        return "Stop Duration"
    elif name.startswith("violation_raw"):
        return "Violation Raw"
    elif name.startswith("violation_"):
        return "Violation"
    elif name.startswith("driver_race"):
        return "Driver Race"
    elif name.startswith("driver_"):
        return "Driver"
    elif name.startswith("stop_wday"):
        return "Stop Weekday"
    else:
        return "Other"

tabla_bin["Category"] = tabla_bin.index.map(cats)

tabla_bin = tabla_bin.sort_values(["Category", "Count_1s"], ascending=[True, False])

tabla_bin["Proportion"] = (tabla_bin["Proportion"] * 100).round(1)

tabla_bin = tabla_bin[["Category", "Proportion", "Count_1s"]]

#tabla_bin2 = (tabla_bin.style.format({'Proportion': '{:.1f}%', 'Count_1s': '{:,}'}))

tabla_bin["Proportion"] = tabla_bin["Proportion"].map(lambda x: f"{x:.1f}%")
tabla_bin["Count_1s"] = tabla_bin["Count_1s"].map("{:,}".format)

print("Numeric features:")
print(tabla_num)

print("\nBinary fetures:")
print(tabla_bin)
###

###
cols_outcome = [i for i in ds5.columns if i.startswith("stop_outcome_")]

cols_race = ["driver_race_Asian", "driver_race_Black", "driver_race_Hispanic", "driver_race_Other", "driver_race_White"]

cols_actions = ["search_conducted","is_arrested","drugs_related_stop"]

###

###
def resultados_raza(columnas):
    filas = {}
    for i in cols_race:
        a = ds5[i] == 1
        nombre = i.replace("driver_race_", "Race: ")
        if a.any():
            filas[nombre] = ds5.loc[a, columnas].mean()
    return pd.DataFrame(filas).T

resultados2 = resultados_raza(cols_outcome + cols_actions).mul(100).round(1)
resultados3 = resultados2.astype(str) + '%'

print("Outcome by race:")
print(resultados3.to_string())

###

###
resultados_genero = (ds5.groupby("driver_gender")[cols_outcome + cols_actions].mean().mul(100).round(1).rename(index={0:"Female", 1:"Male"}))
resultados_genero2 = resultados_genero.astype(str) + '%'

print("Outcome by gender:")
print(resultados_genero2.to_string())
###

###
det_hora = ds5.groupby("stop_hour").size()
det_hora2 = (det_hora / det_hora.sum() * 100).round(1)
det_hora3 = det_hora2.astype(str) + '%'

print("Stops by Hour:")
print(det_hora3)
###

###
plt.figure()
ds5['driver_age'].dropna().plot(kind='hist', bins=30, edgecolor='black')
plt.title('Edades de conductores')
plt.xlabel('Edad')
plt.ylabel('Conductores')
plt.show()
###

###
det_hora = ds5.groupby('stop_hour').size()
plt.figure()
det_hora.plot(kind='bar')
plt.title('Detenciones por hora')
plt.xlabel('Hora')
plt.ylabel('Detenciones')
plt.show()
###

###
cols_race = [i for i in ds5.columns if i.startswith('driver_race_')]
arrested = ds5[ds5['stop_outcome_Arrest Driver'] == 1]
arrest_n = arrested[cols_race].sum().sort_values(ascending=False)
plt.figure()
plt.pie(arrest_n.values, labels=[x.replace('driver_race_', '') for x in arrest_n.index], autopct='%1.1f%%', startangle=90)
plt.title('Conductores arrestados por raza')
plt.show()
###

###
arrested_e = ds5.loc[ds5['stop_outcome_Arrest Driver'] == 1, 'driver_age']
plt.figure()
arrested_e.plot(kind='hist', bins=30, edgecolor='black')
plt.title('Edades de conductores arrestados')
plt.xlabel('Edad')
plt.ylabel('Conductores')
plt.show()
###

###
plt.figure()
ds5.boxplot(column='driver_age', by='stop_hour', grid=False)
plt.title('Edad de conductores por hora de detencion')
plt.suptitle('')
plt.xlabel('Hora')
plt.ylabel('Edad')
plt.show()
###

resumen_anual = (ds5.groupby('stop_year').agg(total_stops = ('driver_gender', 'size'), total_arrestos = ('is_arrested', 'sum'), edad_promedio = ('driver_age', 'mean')).reset_index())
resumen_anual['prop_arrestos'] = resumen_anual['total_arrestos'] / resumen_anual['total_stops']
print(resumen_anual.head())

def ajusta_recta(x_vals, y_vals):
    m, b = np.polyfit(x_vals, y_vals, 1)
    y_ajustada = m * x_vals + b
    return m, b, y_ajustada

###
x_years = resumen_anual['stop_year'].values.astype(float)
y_stops = resumen_anual['total_stops'].values.astype(float)
m_stops, b_stops, y_stops_fit = ajusta_recta(x_years, y_stops)
###

###
print("Pendiente detenciones/año:", m_stops)
print("Intercepto:", b_stops)
###

###
plt.figure(figsize=(8,4))
plt.plot(x_years, y_stops, 'o-', label='Detenciones reales')
plt.plot(x_years, y_stops_fit, '--', color='red', label='Linea ajustada')
plt.xlabel('Año')
plt.ylabel('Numero de detenciones')
plt.title('Tendencia anual de detenciones')
plt.legend()
plt.tight_layout()
plt.show()
###

###
n_futuro = 8
ultimo_anio = int(resumen_anual['stop_year'].max())
anios_futuros = np.arange(ultimo_anio + 1, ultimo_anio + 1 + n_futuro, dtype=float)
stops_futuros = m_stops * anios_futuros + b_stops
forecast_anual = pd.DataFrame({'anio': anios_futuros.astype(int), 'stops_pred': np.round(stops_futuros).astype(int)})
###

###
print("Pronostico anual (detenciones totales):")
print(forecast_anual)
###

###
x_years2 = resumen_anual['stop_year'].values.astype(float)
y_prop = resumen_anual['prop_arrestos'].values.astype(float)
m_prop, b_prop, y_prop_fit = ajusta_recta(x_years2, y_prop)
###

###
print("Pendiente proporcion de arrestos/año:", m_prop)
###

###
plt.figure(figsize=(8,4))
plt.plot(x_years2, y_prop, 'o-', label='Proporción real')
plt.plot(x_years2, y_prop_fit, '--', color='green', label='Línea ajustada')
plt.xlabel('Año')
plt.ylabel('Proporción de arrestos')
plt.title('Tendencia anual de proporción de arrestos')
plt.legend()
plt.tight_layout()
plt.show()
###

###
x_years3 = resumen_anual['stop_year'].values.astype(float)
y_age = resumen_anual['edad_promedio'].values.astype(float)
m_age, b_age, y_age_fit = ajusta_recta(x_years3, y_age)
###

###
print("Pendiente edad promedio/año:", m_age)
###

###
plt.figure(figsize=(8,4))
plt.plot(x_years3, y_age, 'o-', label='Edad promedio real')
plt.plot(x_years3, y_age_fit, '--', color='orange', label='Línea ajustada')
plt.xlabel('Año')
plt.ylabel('Edad promedio')
plt.title('Tendencia anual de la edad de los conductores detenidos')
plt.legend()
plt.tight_layout()
plt.show()
###